export interface Dream {
  age: 12,
  amount: 150,
  categoryIds: "[1, 2, 4, 5]",
  cityId: 1,
  dateEnd: "2023-06-30",
  dateStart: "2023-06-30",
  description: "My dream for my dog...",
  donatesIds: "[1, 2, 4, 5]",
  dreamTypeId: 1,
  filename: "picture.jpg",
  id: 1,
  imageData: "string",
  likes: 10,
  mimeType: "image/jpeg",
  name: "My dog",
  statusName: "string",
  sumOfDonates: 125.35,
  userId: 1
}